news/core/views.py
from news.models import News
from flask import render_template, request, Blueprint


core = Blueprint('core', __name__)


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    all_news = News.query.order_by(
        News.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', all_news=all_news)


@core.route('/popular')
def popular():
    page = request.args.get('page', 1, type=int)
    all_news = News.query.order_by(
        News.likes.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', all_news=all_news)


@core.route('/info')
def info():
    return render_template('info.html')

news/news_group/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from news import db
from news.models import News, Comment, Likes
from news.news_group.forms import NewsForm, CommentForm, LikesForm, DislikesForm, SearchForm
from news.picture_handlers import add_news_pic

news_group = Blueprint('news_group', __name__)


# create news manually
@news_group.route('/create', methods=['GET', 'POST'])
@login_required
def create_news():
    form = NewsForm()

    if form.validate_on_submit():
        new_news = News(title=form.title_news.data,
                        text=form.text_news.data, user_id=current_user.id,
                        picture_link=form.picture_link.data, link=form.link.data)

        db.session.add(new_news)
        db.session.commit()
        flash('News Created')
        return redirect(url_for('core.index'))

    return render_template('create_news.html', form=form)

# view news
@news_group.route('/news/<int:news_id>', methods=['GET', 'POST'])
def news_view(news_id):
    form_comment = CommentForm()
    form_likes = LikesForm()
    form_dislikes = DislikesForm()
    news_view = News.query.get_or_404(news_id)
    like = Likes.query.filter_by(
        user_id=current_user.id, news_id=news_id).first()

    if form_comment.submit_comment.data and form_comment.validate():

        comment = Comment(text=form_comment.text.data, news_id=news_id,
                          user_name=current_user.username)

        db.session.add(comment)
        db.session.commit()
        flash('Comment Added')
        return redirect(url_for('news_group.news_view', news_id=news_id))

    if form_likes.submit_like.data and form_likes.validate():
        new_like = Likes(user_id=current_user.id, news_id=news_id)
        news_view.likes += 1
        db.session.add(new_like)
        db.session.commit()
        return redirect(url_for('news_group.news_view', news_id=news_id))

    if form_dislikes.submit_dislike.data and form_dislikes.validate():
        news_view.likes -= 1
        db.session.delete(like)
        db.session.commit()
        return redirect(url_for('news_group.news_view', news_id=news_id))

    comments = Comment.query.order_by(
        Comment.date.desc()).filter_by(news_id=news_id)

    return render_template('view_news.html', title=news_view.title, date=news_view.date, news=news_view, form_comment=form_comment, form_likes=form_likes, form_dislikes=form_dislikes, comments=comments, news_id=news_id, like=like)


# update news
@news_group.route("/<int:news_id>/update", methods=['GET', 'POST'])
@login_required
def update(news_id):
    new_news = News.query.get_or_404(news_id)
    if new_news.author != current_user:

        abort(403)

    form = NewsForm()
    if form.validate_on_submit():
        new_news.title = form.title_news.data
        new_news.text = form.text_news.data
        new_news.picture_link = form.picture_link.data
        db.session.commit()
        flash('News Updated')
        return redirect(url_for('news_group.news_view', news_id=new_news.id))

    elif request.method == 'GET':
        form.title_news.data = new_news.title
        form.text_news.data = new_news.text
        form.picture_link.data = new_news.picture_link
        form.link.data = new_news.link
    return render_template('create_news.html', title='Update', form=form)

# delete news
@news_group.route('/<int:news_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_news(news_id):
    news = News.query.get_or_404(news_id)

    if news.author != current_user:
        abort(403)

    db.session.delete(news)
    db.session.commit()
    flash('News Deleted')
    return redirect(url_for('core.index'))


@news_group.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    search_word = request.args['search_word']
    found_news = News.query.filter(News.title.like(
        '%' + search_word + '%'))

    return render_template('search.html', found_news=found_news)

news/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from news import db, get_google_provider_cfg, client, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
from news.models import User, News
from news.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from news.picture_handlers import add_profile_pic
import requests
import json

users = Blueprint('users', __name__)

# Login with google
@users.route("/google_login")
def google_login():
    # Find out what URL to hit for Google login
    google_provider_cfg = get_google_provider_cfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    # Use library to construct the request for Google login and provide
    # scopes that let you retrieve user's profile from Google
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@users.route("/google_login/callback")
def callback():
    code = request.args.get("code")

    google_provider_cfg = get_google_provider_cfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code,
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
    )

    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)

    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]
        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
        print(userinfo_response.json())

    else:
        return "User email not available or not verified by Google.", 400

    user = User.query.filter_by(email=users_email).first()

    if user:
        login_user(user)
        return redirect(url_for("core.index"))
    else:
        return render_template("no_login.html")


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        if form.check_email(form.email) == False:
            return redirect(url_for('users.register'))
        elif form.check_username(form.username) == False:
            return redirect(url_for('users.register'))
        else:
            user = User(email=form.email.data,
                        username=form.username.data,
                        password=form.password.data)

            db.session.add(user)
            db.session.commit()
            flash('Thanks for registration!')
            return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            return render_template("no_login.html")

        elif not user.check_password(form.password.data):
            flash('Email and password do not match')
            return redirect(url_for('users.login'))

        elif user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html', form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()
    page = request.args.get('page', 1, type=int)
    user_news = News.query.filter(
        News.user_id == current_user.id).order_by(
        News.date.desc()).paginate(page=page, per_page=5)

    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        elif form.check_email(form.email) == False:
            return redirect(url_for('users.account'))
        elif form.check_username(form.username) == False:
            return redirect(url_for('users.account'))

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for(
        'static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form, user_news=user_news)


@users.route("/<username>")
def user_news(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    user_news = News.query.filter(
        News.user_id == current_user.id).order_by(
        News.date.desc()).paginate(page=page, per_page=5)

    return render_template('user_news.html', user_news=user_news, user=user)

news/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="user_info">
    <div>
      <img src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
      <p>{{ current_user.username }}</p>
    </div>
    <div>
      <a id="update_user" href="#" class="btn btn-primary">Update Details</a>
    </div>
  </div>

  <div id="user_update_form" class="hidden">
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username.label(class="form-group") }}
        {{form.username(class='form-control')  }}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-group") }}
        {{form.email(class='form-control')  }}
      </div>
      <div class="form-group">
        {{ form.picture.label(class="form-group") }}
        {{ form.picture(class="form-control-file") }}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
  {% for mess in get_flashed_messages() %}
  <br>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{mess}}
  </div>
  {% endfor %}
  <br>

  <h3>News added by you:</h3>
  <br>
  {% if not user_news.items %}
  <h4>No news yet!</h4>
  {% else %}

  {% for news in user_news.items %}
  <div class="card">
    <div class="card-body">
      <div class='likes'>
        <div class="news_counter">{{news.likes}}</div>
      </div>
      <div class="miniature">
        {% if news.picture_link%}
        <img class="miniature_img" src="{{news.picture_link}}" alt="miniature">
        {% else %}
        <img src="{{ url_for('static', filename='default.jpeg') }}">
        {% endif %}
      </div>
      <div class="news_info">
        <h2><a class="card-title" href="  {{ url_for('news_group.news_view', news_id=news.id) }}">{{ news.title }}</a>
        </h2>
        <p>Published on: {{ news.date.strftime('%d-%m-%Y') }}</p>
        <p class="card-text">{{ news.text[:100] }}...</p>
      </div>
    </div>
    <div class="controls">
      <div>
        <a href="{{ url_for('news_group.news_view', news_id=news.id) }}" class="details_btn btn btn-primary">Details</a>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination ">
    {% for page_num in user_news.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if user_news.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link" href="{{ url_for('users.account', page=page_num) }}">{{ page_num }}</a></li>
    </li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{ url_for('users.account', page=page_num) }}">{{ page_num }}</a>
    </li>
    {% endif %}
    {% endfor %}
</nav>



{% endblock content %}

news/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
    integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
  <link href="{{ url_for('static', filename='css/main.css')}}" rel="stylesheet" />

  <title>NewsDig</title>
</head>

<body>
  <nav id="navbar">
    <ul>
      <div class="nav-link">
        <a id="home" href="{{url_for('core.index')}}"><i class="fas fa-kiwi-bird"></i>NewsDig</a>
      </div>
      <li class="nav-link">
        <a href="{{url_for('core.popular')}}">Popular</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('core.info')}}">About</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('news_group.create_news')}}">Add News</a>
      </li>
    </ul>
    <ul>
      <div class="nav-link">
        <form id="search_form" action="{{ url_for('news_group.search') }}">
          <div>
            <input type="text" id="search_word" name="search_word" placeholder="Search" required />
          </div>
          <button type="submit" id="button-addon2">
            Search<i class="fas fa-search"></i>
          </button>
        </form>
      </div>
      {% if current_user.is_authenticated %}
      <li class="nav-link">
        <a href="{{url_for('users.logout')}}">Log Out</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('users.account')}}"><i class="fas fa-user-alt"></i>Account
        </a>
      </li>

      {% else %}
      <li class="nav-link">
        <a href="{{url_for('users.login')}}">Log In</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('users.register')}}">Register</a>
      </li>
      {% endif %}
    </ul>
  </nav>

  <div class="container">
    {% block content %} {% endblock %}
  </div>

  <footer>
    <p>Copyrights &copy; 2020 </p>
  </footer>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
  <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

news/templates/create_news.html
{%extends 'base.html'%}
{%block content%}
{% for field, errors in form.errors.items() %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {{ ', '.join(errors) }}
</div>
{% endfor %}

<div class="container">
  <form class="form-group" method="POST">
    {{form.hidden_tag()}}
    <div class="form-group news-link-btn">
      {{ form.link.label(class="form-group label") }} {{
      form.link(class="form-control-file") }}
    </div>

    <div class="form-group  ">
      {{form.title_news.label(class='form-control-label label')}}
      {{form.title_news(class='form-control form-control-lg')}}
    </div>
    <div class="form-group ">
      {{form.text_news.label(class='form-control-label label')}}
      {{form.text_news(class='form-control form-control-lg')}}
    </div>
    <div class="form-group ">
      {{ form.picture_link.label(class="form-group label") }} {{
      form.picture_link(class="form-control-file") }}
    </div>

    <div class="form-group submit-news">
      {{form.submit_news(class='btn btn-primary')}}
    </div>
  </form>
</div>
{%endblock%}

news/templates/index.html
{% extends "base.html" %}
{% block content %}
{% for mess in get_flashed_messages() %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{mess}}
</div>
{% endfor %}

{% for news in all_news.items %}

<div class="card">
    <div class="card-body">
        <div class='likes'>
            <div class="news_counter">{{news.likes}}</div>
        </div>
        <div class="miniature">
            {% if news.picture_link%}
            <img class="miniature_img" src="{{news.picture_link}}" alt="">
            {% else %}
            <img src="{{ url_for('static', filename='default.jpeg') }}">
            {% endif %}
        </div>
        <div class="news_info">
            <h2><a class="card-title"
                    href="  {{ url_for('news_group.news_view', news_id=news.id) }}">{{ news.title }}</a></h2>
            <p>Added by:<a href="{{ url_for('users.user_news', username=news.author.username) }}">
                    {{ news.author.username }}</a></p>
            <p>Published on: {{ news.date.strftime('%d-%m-%Y') }}</p>
            <p class="card-text">{{ news.text[:100] }}...</p>
        </div>
    </div>
    <a href="{{ url_for('news_group.news_view', news_id=news.id) }}" class="details_btn btn btn-primary">Details</a>
</div>

{% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination ">
        {% for page_num in all_news.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if all_news.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
</nav>
{% endblock %}

news/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="card">
    <div id="about">
        <h1>Newsdig</h1>
        <p>Find the most interesting news dug by our community.</p>
    </div>
</div>
{% endblock %}

news/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div id="login">
    <h2>Login</h2><br>
    {% for mess in get_flashed_messages() %}
    <br>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{mess}}
    </div>
    {% endfor %}

    {% for field, errors in form.errors.items() %}
    <br>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ ', '.join(errors) }}
    </div>
    {% endfor %}
    <br>
    <form method="POST">
      {{form.hidden_tag()}}
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="far fa-envelope-open"></i></div>
        </div>
        {{form.email(class="form-control form-control-lg",placeholder="Email")}}<br><br>
      </div>
      <br>
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-lock"></i></div>
        </div>
        {{form.password(class="form-control form-control-lg",placeholder="Password")}}<br><br>
      </div>
      <br>
      <a class="btn btn-info" id="google_btn" href="{{url_for('users.google_login')}}"><i class="fab fa-google"></i>
        Sign in using
        Google</a>
      {{form.submit(class="btn btn-success")}}
    </form>
  </div>
</div>
{% endblock %}

news/templates/no_login.html
{% extends "base.html"%} {% block content %}
<h2 id="no-login">We couldn't find your details, please register first.</h2>

{% endblock %}

news/templates/search.html
{% extends "base.html" %}
{% block content %}
{% for news in found_news %}
<div class="card">
    <div class="card-body">
        <div class='likes'>
            <div class="news_counter">{{news.likes}}</div>
        </div>
        <div class="miniature">
            {% if news.picture_link%}
            <img class="miniature_img" src="{{news.picture_link}}" alt="">
            {% else %}
            <img src="{{ url_for('static', filename='default.jpeg') }}">
            {% endif %}
        </div>
        <div class="news_info">
            <h2><a class="card-title"
                    href="  {{ url_for('news_group.news_view', news_id=news.id) }}">{{ news.title }}</a></h2>
            <p>Added by:<a href="{{ url_for('users.user_news', username=news.author.username) }}">
                    {{ news.author.username }}</a></p>
            <p>Published on: {{ news.date.strftime('%d-%m-%Y') }}</p>
            <p class="card-text">{{ news.text[:100] }}...</p>
        </div>
    </div>
    <a href="{{ url_for('news_group.news_view', news_id=news.id) }}" class="details_btn btn btn-primary">Details</a>
</div>
{% endfor %}
{% endblock %}

news/templates/user_news.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align='center'>
            <h1>Welcome to the page for {{user.username}}</h1>
            <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
        </div>
    </div>

    {% if not user_news.items %}
    <h4>No news yet!</h4>
    {% else %}

    {% for news in user_news.items %}
    <div class="card">
        <div class="card-body">
            <div class='likes'>
                <div class="news_counter">{{news.likes}}</div>
            </div>
            <div class="miniature">
                {% if news.picture_link%}
                <img class="miniature_img" src="{{news.picture_link}}" alt="">
                {% else %}
                <img src="{{ url_for('static', filename='default.jpeg') }}">
                {% endif %}
            </div>
            <div class="news_info">
                <h2><a class="card-title"
                        href="  {{ url_for('news_group.news_view', news_id=news.id) }}">{{ news.title }}</a>
                </h2>
                <p>Published on: {{ news.date.strftime('%d-%m-%Y') }}</p>
                <p class="card-text">{{ news.text[:100] }}...</p>
            </div>
        </div>
        <a href="{{ url_for('news_group.news_view', news_id=news.id) }}" class="details_btn btn btn-primary">Details</a>
    </div>
    {% endfor %}
    {% endif %}
</div>

<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
        {% for page_num in user_news.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
        {% if user_news.page == page_num %}
        <li class='page-item disabled'>
            <a class="page-link"
                href="{{url_for('users.user_news',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
            <a class="page-link"
                href="{{url_for('users.user_news',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</nav>




{% endblock %}

news/templates/view_news.html
{%extends 'base.html'%}
{%block content%}

{% for mess in get_flashed_messages() %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{mess}}
</div>
{% endfor %}


<div class="container">
    <div class="card">
        <div class="card-body">
            <div class='likes'>
                <div class="news_counter">{{news.likes}}</div>
                {% if current_user.id==like.user_id and news_id == like.news_id%}
                <div class="dislike">
                    <form class='form-group' method='POST'>
                        {{form_dislikes.hidden_tag()}}
                        <div class="form-group">
                            {{form_dislikes.submit_dislike(class='btn btn-outline-info')}}
                        </div>
                    </form>
                </div>
                {% else %}

                <div class="like">
                    <form class='form-group' method='POST'>
                        {{form_likes.hidden_tag()}}

                        <div class="form-group">
                            {{form_likes.submit_like(class='btn btn-outline-info')}}
                        </div>
                    </form>
                </div>
                {% endif %}
            </div>
            <div class="miniature">
                {% if news.picture_link%}
                <img class="miniature_img" src="{{news.picture_link}}" alt="">
                {% else %}
                <img src="{{ url_for('static', filename='default.jpeg') }}">
                {% endif %}
            </div>
            <div class="news_info_view">
                <h2>{{ news.title }}</h2>
                <p class="card-text">{{ news.text}}</p>
                <p>Added by: <a
                        href="{{ url_for('users.user_news', username=news.author.username) }}">{{ news.author.username }}</a>
                </p>
            </div>
        </div>
        {%if news.author == current_user%}
        <div class='update_delete'>
            <a href="{{url_for('news_group.update',news_id=news.id)}}">Update</a>&nbsp;
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
        </div>
        {%endif%}
        <a href="{{news.link}}"><button type="button" class="btn btn-success source">Go to the source</button></a>

    </div>


    {% for comment in comments %}
    <div class="comment">
        <p>- {{comment.text}}</p>
        <p>&nbsp;&nbsp;&nbsp;By:<a href="{{ url_for('users.user_news', username=comment.user_name) }}">
                {{comment.user_name}}</a></p>

    </div>
    {% endfor %}



    {% if current_user.is_authenticated %}
    <form class='form-group comment-form' method='POST'>
        {{form_comment.hidden_tag()}}
        <div class="form-group">
            {{form_comment.text.label(class='form-control-label comment-label')}}
            {{form_comment.text(class='form-control form-control-lg comment-field')}}
        </div>
        <div class="form-group">
            {{form_comment.submit_comment(class='btn btn-outline-info submit_comment')}}
        </div>
    </form>
    {% endif %}
</div>


<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete News?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the news?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                <form action="{{url_for('news_group.delete_news',news_id=news.id)}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}